-- Historical package index migration intentionally disabled.
--
-- The legacy package index schema has been retired.
-- The current architecture uses artifacts as the source of truth and packages
-- only as a rebuildable package summary read model.
