-- Historical package index -> artifacts migration intentionally disabled.
-- The current artifact schema uses structured columns (name, version, path,
-- filename, remote_path, qualifiers, attributes, metadata) and no longer
-- supports the legacy artifact identity JSON column. Historical data is not migrated.
